// <auto-generated />
using System;
using AuthorMicroservice.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthorMicroservice.Migrations
{
    [DbContext(typeof(AuthorContext))]
    [Migration("20230519202421_dateTime2")]
    partial class dateTime2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorMicroservice.Model.AcademicGrade", b =>
                {
                    b.Property<int>("IdAcademicGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAcademicGrade"));

                    b.Property<string>("AcademicGradeGuid")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorIdAuthor")
                        .HasColumnType("integer");

                    b.Property<string>("CenterAcademic")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateGrade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAuthor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("IdAcademicGrade");

                    b.HasIndex("AuthorIdAuthor");

                    b.ToTable("AcademicGrades");
                });

            modelBuilder.Entity("AuthorMicroservice.Model.Author", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuthor"));

                    b.Property<string>("AuthorGuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("IdAuthor");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("AuthorMicroservice.Model.AcademicGrade", b =>
                {
                    b.HasOne("AuthorMicroservice.Model.Author", "Author")
                        .WithMany("AcademicGrades")
                        .HasForeignKey("AuthorIdAuthor");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AuthorMicroservice.Model.Author", b =>
                {
                    b.Navigation("AcademicGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
